spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://mainline.proxy.rlwy.net:28437/railway}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:zbPJGPMNyPvurRvJZqLBFZpxMYYwDyzd}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  # Email Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:healthconnectwebsite@gmail.com}
    password: ${MAIL_PASSWORD:juzd kqem ivhv tksh}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  # Multipart file config
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${SERVER_PORT:8080}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:defaultSecretKeyThatShouldBeReplacedInProduction}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds 

# OTP Configuration
otp:
  expiration: ${OTP_EXPIRATION:300000} # 5 minutes in milliseconds
  length: ${OTP_LENGTH:6}

# Google Cloud Storage Configuration
gcp:
  storage:
    # You should replace these values with your actual GCP bucket details
    bucket-name: ${GCP_BUCKET_NAME:healthconnect-bucket}
    credentials-file-path: ${GCP_CREDENTIALS_PATH:classpath:gcp-credentials.json}
    base-url: ${GCP_BASE_URL:https://storage.googleapis.com} 