spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://mainline.proxy.rlwy.net:28437/railway}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:zbPJGPMNyPvurRvJZqLBFZpxMYYwDyzd}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:defaultSecretKeyThatShouldBeReplacedInProduction}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds 